Repository adithyapaib/Neomorphic-PortfolioTemplate, pull requests merged in 2021-10, with the labels that each got.

#11 feat : added template preview
  README.md
  assets/img/preview-1.PNG
  assets/img/preview-2.PNG
  assets/img/preview-3.PNG
Labels: good first issue, hacktoberfest-accepted

#15 Update README.md
  README.md
Labels: hacktoberfest-accepted

#14 Icons aligned properly
  assets/css/_about.scss
  assets/css/main.css
Labels: enhancement, hacktoberfest-accepted

#17 Add icons and reference links in README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#23 Changed the padding in footer and remove text line in anchor tag, added hover color in anchor tag
  assets/css/_footer.scss
  assets/css/main.css
Labels: good first issue, hacktoberfest-accepted

#26 redirected all the social media link in Connect to new tab
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#54 Update index.html
  index.html
Labels: help wanted, good first issue, hacktoberfest-accepted, OP moment

#48 Improved Social Media Icons #19
  assets/css/main.css
  index.html
Labels: help wanted, hacktoberfest-accepted, OP moment, Sed moment

#66 Updated meta :description tag
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#63 Updated Resume button.
  index.html
Labels: good first issue, hacktoberfest-accepted, OP moment

#43 Added Icons in Readme file
  README.md
Labels: good first issue, hacktoberfest-accepted, Sed moment

#68 Add a Project Section
  assets/css/main.css
  assets/img/project.jpg
  index.html
Labels: enhancement, hacktoberfest-accepted, OP moment

#53 footer updated
  assets/css/_footer.scss
  assets/css/main.css
Labels: duplicate, enhancement, good first issue, Sed moment

#81 grammatical error solved.
  README.md
Labels: good first issue, hacktoberfest-accepted

#73 added Go back to Top Button
  assets/css/main.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#74 FIX the recent PROJECT HEADING
  assets/css/main.css
Labels: good first issue, hacktoberfest-accepted

#78 Updated main.css
  assets/css/main.css
Labels: good first issue, hacktoberfest-accepted

#79 Fixed the ISSUE #72 and #77
  assets/css/main.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#94 fix back to top button
  assets/css/main.css
  index.html
Labels: help wanted, hacktoberfest-accepted
